spring.application.name=data-hub
server.port=8084
spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}

# ----------------------------
# MongoDB (externalized)
# ----------------------------
spring.mongodb.uri=mongodb://localhost:27017/data_hub_test
spring.data.mongodb.auto-index-creation=${MONGODB_AUTO_INDEX_CREATION:true}

# ----------------------------
# Kafka consumer
# ----------------------------
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:data-hub-consumer}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.admin.auto-create=true
spring.kafka.listener.ack-mode=manual_immediate
spring.kafka.listener.concurrency=${KAFKA_CONCURRENCY:3}

# ----------------------------
# Application-specific
# ----------------------------
app.kafka.topic.raw-events=${APP_KAFKA_TOPIC_RAW_EVENTS:data-hub.raw-events}
app.kafka.topic.raw-events.partitions=${APP_KAFKA_TOPIC_RAW_EVENTS_PARTITIONS:3}
app.kafka.topic.raw-events.replicas=${APP_KAFKA_TOPIC_RAW_EVENTS_REPLICAS:1}
app.security.admin.username=${APP_ADMIN_USERNAME:admin}
app.security.admin.password=${APP_ADMIN_PASSWORD:admin123}
app.security.report.username=${APP_REPORT_USERNAME:reporter}
app.security.report.password=${APP_REPORT_PASSWORD:report123}

app.kafka.listener.enabled=true
app.kafka.producer.enabled=${APP_KAFKA_PRODUCER_ENABLED:true}
app.kafka.producer.interval-ms=${APP_KAFKA_PRODUCER_INTERVAL_MS:3000}
app.kafka.producer.batch-size=${APP_KAFKA_PRODUCER_BATCH_SIZE:3}
app.kafka.producer.initial-delay-ms=${APP_KAFKA_PRODUCER_INITIAL_DELAY_MS:3000}
app.kafka.producer.max-events=${APP_KAFKA_PRODUCER_MAX_EVENTS:300000}
app.kafka.producer.event-type=${APP_KAFKA_PRODUCER_EVENT_TYPE:BET}
app.kafka.producer.source=${APP_KAFKA_PRODUCER_SOURCE:systemA}
app.kafka.producer.user-name=${APP_KAFKA_PRODUCER_USER_NAME:Vy Nguyen}
app.event.processing.timeout-ms=${APP_EVENT_PROCESSING_TIMEOUT_MS:10000}
